apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-wg
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:X77C538AX9B2RY5YnUZkXERg449s2N1gr75ei/yaSdCmgaDz5rpOostTy12eiXrbODDgY8DR6gTvXZdOKA3MGutbj8VB6msKojFbASN88gHe3vXnrRviGDQfyIoVbfp82D1RJim/MmMttaVAQrTO/+pfoly04TSAZUnG/wd2bpBwWRUcrhi868/hXQWf1Xy+G8g1cynPBxR5SkDIgqGrN6KS8OBl28mmJAkapb18hSYhTXsjm/Q+SviM5/syQbE6Ql1/sfeztPsHWCVa/YYQqTt0QeXwr65fBuHZBkdBI2ffP4xthlRpQX3msLoWP4QHxBTx145zANhFBFenMO0uVnmA8cf6zXWV4BbnN/eWfA3VUHD/xaJ4F2liLUpeoeVGWh9McBCdgdrXiYXB8uJzse6AOezelWXY68T3WxwmiHoKXtgVaCI/t2wbpzrpaQyp442AxvG9JlH/NEH8El+Rb6inFniNdggVa1pAE2K5+KhpuFgTv1R5obXv8x8PDqYmpj01Kyyyrk3iXa+GOdoIqUR1vivPye4/U1m7GKma8dOgMXOkYRTy+zU48x22QP9WrO70oKKX5spBsI+focM7nedLlCWjLdDO/Lkx5rHv0NZGjNJQzxMRMGNmwLxOAG33ChxQyIOYe11Z8XJpkD2L9bpyUiRk7d/8zWCaDTDAU9ZN89V1nSTUHQESg0WCGPLrM9d9mjK2+45XwcuovaM71gNOFfcNq8ds/rsumLL+K6UR6khoPelw7OE89BKg1s0dpAIhlFeGVrkFmOOV5PTY3MlUnrfeRX0P8t7vujKt4RlXcXga8uzi1B4mLofxbmzjqL3HHUS7Q/d3gJzEIi/I03njGpc2z4OQxyOYgalFJjeMicrr48dmBs0++RG3raypPm/aE/Na+MO/xUZ029RD6LH3wmmWEmnxWjyMs5A+pTb2uifwm7jmxYkgP2tqz/iRJ+OJ4y7hi+hoyLsiTjjWsPA79DedH4iUd67bgQC9OI4f319aNiEYFWj08qdtyKQ5X6haM6/JLBKCxK7OItiCFvO4eWCmoj4eeTUqS6BhxMC5OyFqPjC5bz8hvOtQP1wtftXbESRQcFCzzDaBFLvGTj2iN5Y9jrJk2eg9TaQu2q6mFaLOZogVpDt7GIe60phQZCLuKov/Hfdi6rYkLTCQBvuyNA7+t+8tSW+8uJAx/c0YrUESwkKN1jGKvOCiIW5jCsOzi7z31/NrDKCVGwW+pS1NFWfOWn0=,iv:NFkTJQS3QSX8bFPbuu/fw+XSbpPz6BBWq0z6/BQxJV0=,tag:gKGcQPRq9z1u/R6Vl+mgGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWEpWZFBHa2l4Vk1TZjBW
            TXVuVVJ5aFovbFNNOXN2ZXl2VG9wanFaSkZnClE1MEFKd2puQWUvU0o4Yy9vRzVi
            cGhvYU9CdzN2dEdGenJtQmt0MkVNUWsKLS0tIEoxMDRHMlI5aUtDSDdmRnBZUkQy
            Yld4Q2xhZ3FITjRJMUpqVTJxUkVGUDQKRXNN9lNGrFbs7A8ioOn+WrBqcrjsP3+n
            XyGaELHXb8kbaOh7FIVzxpH0sYYkudBpV9HVXSMgyDrTy2z2EVQeGg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T09:56:20Z"
    mac: ENC[AES256_GCM,data:T8tp2z0JZjHxQNX2vW8U8IJSnVcxXWEUqRtZfgmEDoQSUdlWulX77/Kp/IioBxiyh5wM6pvNU2KbFcwuOqBnUc688k5TO9is2b3BZhtzDs0mCc0joJXgicO7j4nTT7neOu30bw/fINjeWDrcJPdKzaxbfpcdcoBnQD5WaS472qA=,iv:fPoHT4QmUcqqTL7qDD2XAWn3rn3wun6zimxkamM1/2Y=,tag:d6AAdzgLRe0BvxCVolLkyA==,type:str]
    version: 3.13.2
