apiVersion: v1
kind: Secret
metadata:
    name: open-webui-tools-secrets
    namespace: default
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:ZATpu/z1YPg2GGrqpBXPlayTgRTZwlwjixVex/gkI2Sj2jyvJf+j3Kb1ieR/Q3jgYJVjztQf3Y210ab42xjgBa0=,iv:rG0MRFeAN40iekjdN3F/yIr6cmgFW1ZheuCzsKfRp58=,tag:0Xt01S7PS3/XpoPVEwjDKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWM2dOcXp3S2plb3NhZmZO
            SFZ3NGM5eUNoRnF2UjZmOW1oVFU4UkRJUFRjClpWZS8vWTFYR080d1gvQTNPblpG
            OUt0UTRXOElqeTgvTDFQU3RMbElIczgKLS0tIDk0QlJLK2VGbjJkdXgxVUhNZDc1
            SzRmQVNVaGEyZjR1WlNjUnhBRFNUMDQKo2lHcTdRb5fqxpH8iPYK53JqAgqDEdRG
            Dnol1/bzTGlW55FmfjvjkKIr4VV3P4VUmPMRNaI6ejgkHtSTA079kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-10T20:47:13Z"
    mac: ENC[AES256_GCM,data:X1yv4GAIXn5XLxrpuy9Ru1gkXmqEX5ffQhGg8swXhcf2+aDSfkr0ll2wcendXuXCSnVfzaF3eWr1lpKNRKAkTINyAGmubsjR27VCW6pJzwzNrsN0RvmtJ48y3dZ8FRE3PXQdL8usWVPRSLpHwZhdE6vGsvFZ2ecrZE39hyzVXQY=,iv:/o5+p+JsaTwTtwOdnGDlltZGVMVIg71DgfzhBKQmgdM=,tag:SduMdK+SO3HBJ/ZQYiCMIw==,type:str]
    version: 3.13.2
