---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-tools
  namespace: default
spec:
  selector:
    app: open-webui-tools
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
