apiVersion: v1
kind: Secret
metadata:
    name: bifrost-secrets
    namespace: default
type: Opaque
stringData:
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:PTtqjvlBDs1R0Ai1jYOluf2A045osyAvKHkWy7oO/DyaZIrFcg+tXRlcr2E=,iv:8rRCk7AoOsjncRjrXY42sKssSH7eIkaCR28pyX/PiYI=,tag:x18o/S2r50amy833X7r5yA==,type:str]
    BIFROST_ADMIN_USERNAME: ENC[AES256_GCM,data:4ApafsI=,iv:3blJFYcBndhVNZ6sFFhqsTfwkjuK6L7YpAC9fTmjSPk=,tag:WUfUXgGSwUMX8SK+4n3kOw==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:kYofdA2AnGLEd150VVgSh8O8N9UOQsfYdd2RZw==,iv:qSai5xDCYwmamPqbJDQJREAg7/YelfagGsWkFapBA8U=,tag:gij+6s+6SNwYVCP/ATQ4EA==,type:str]
    BIFROST_VK_INVOICE: ENC[AES256_GCM,data:u6jfaWqJ/98MTV613kUnGEQEdeKx9SYfeCiJa+F8Fjh81BTckF3S9pRSBescudzplJ0=,iv:R+eY0CewNt+zuFBOlF6snig47yA6XeVBQe4heB7O1Bo=,tag:GMVthUjeJ7pb7UYbzLvtoA==,type:str]
    BIFROST_VK_NOTICE: ENC[AES256_GCM,data:u31wyJljwDZBI45vcQRg2L4G83QYFqbXhU0s1282mSNToqLrDjHsOQcWTOVo2bBriek=,iv:qdXaLMlAHVWHN76xWzpRuFJKCYYIOXghsUhBi8868BM=,tag:uTMCGbtr8dzxelAW/KKW7A==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8xN5mAzZ/LXxbfBdasyx85wirLv8vWr6sJmzucB7aW0Y8BDPRkHD4czuBGvNTFNdjI2Iq14+q1jDN1XllyEEyto4XY7OYh1TAKxc39je0G/X/zTztaJZpX04eem13AZUJ6AWf5eEH++VpyuE,iv:1dQwRkGpt23fmbLwxhgy2p7RQTRDsKmkiSV1TfxmXew=,tag:bSq4O1G/1MVZle9r+ZYAaw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM1UwZWxnTngzWDNWYjc1
            NzZYWHpiSWZhVlBrY2tmdzY2a2pVT24xaTNJCms2d2o0OHFwTitLaEgyMFUrWDlm
            YndUNWo2OVRabU8yS1A5YW5hYmczZUUKLS0tIHRhcU5jU1pvSUpxQUxrWC83NnVo
            a0RvQkR5YytpTjg0V2xIRWg2ditPWWMK1QQHABPX+sm60WVRyLPCgHQzAfxhLBIa
            qqJ4wDFe+oRS1dPZT9EEKSEuO30tdEXJbwFkuaN7cLGZF0PNM741hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T12:37:46Z"
    mac: ENC[AES256_GCM,data:7JXBc3YEXJxOeRILAPz+1vL+5TTxclm8m7TMsQk7txcoG8E/iNrE+3M1XvF2r6I9GqVDaats2lvbkVvD3xgE6/xZgRBh50c4TkwaLlYrBpLxVEYB2osedRrID6oysf8zpqN44MXnfjVyVciKNOG7JTVmQEX0Ue+Hf5XTInTb8Os=,iv:lxCZcqATT4PL6CMEtow2W9RF8xN2YhT6Yl2tTqqVZhA=,tag:Yqg5ZQXSbnqxa5zG7fmqzQ==,type:str]
    version: 3.13.2
