apiVersion: v1
kind: Secret
metadata:
    name: bifrost-secrets
    namespace: default
type: Opaque
stringData:
    BIFROST_ENCRYPTION_KEY: ENC[AES256_GCM,data:PTtqjvlBDs1R0Ai1jYOluf2A045osyAvKHkWy7oO/DyaZIrFcg+tXRlcr2E=,iv:8rRCk7AoOsjncRjrXY42sKssSH7eIkaCR28pyX/PiYI=,tag:x18o/S2r50amy833X7r5yA==,type:str]
    BIFROST_ADMIN_USERNAME: ENC[AES256_GCM,data:4ApafsI=,iv:3blJFYcBndhVNZ6sFFhqsTfwkjuK6L7YpAC9fTmjSPk=,tag:WUfUXgGSwUMX8SK+4n3kOw==,type:str]
    BIFROST_ADMIN_PASSWORD: ENC[AES256_GCM,data:kYofdA2AnGLEd150VVgSh8O8N9UOQsfYdd2RZw==,iv:qSai5xDCYwmamPqbJDQJREAg7/YelfagGsWkFapBA8U=,tag:gij+6s+6SNwYVCP/ATQ4EA==,type:str]
    BIFROST_VK_INVOICE: ENC[AES256_GCM,data:u6jfaWqJ/98MTV613kUnGEQEdeKx9SYfeCiJa+F8Fjh81BTckF3S9pRSBescudzplJ0=,iv:R+eY0CewNt+zuFBOlF6snig47yA6XeVBQe4heB7O1Bo=,tag:GMVthUjeJ7pb7UYbzLvtoA==,type:str]
    BIFROST_VK_NOTICE: ENC[AES256_GCM,data:u31wyJljwDZBI45vcQRg2L4G83QYFqbXhU0s1282mSNToqLrDjHsOQcWTOVo2bBriek=,iv:qdXaLMlAHVWHN76xWzpRuFJKCYYIOXghsUhBi8868BM=,tag:uTMCGbtr8dzxelAW/KKW7A==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:8xN5mAzZ/LXxbfBdasyx85wirLv8vWr6sJmzucB7aW0Y8BDPRkHD4czuBGvNTFNdjI2Iq14+q1jDN1XllyEEyto4XY7OYh1TAKxc39je0G/X/zTztaJZpX04eem13AZUJ6AWf5eEH++VpyuE,iv:1dQwRkGpt23fmbLwxhgy2p7RQTRDsKmkiSV1TfxmXew=,tag:bSq4O1G/1MVZle9r+ZYAaw==,type:str]
    BIFROST_VK_GENERAL: ENC[AES256_GCM,data:RpB0kYkyePqu6ELAshdDifh8p+AMMcY983prWJM13tUtuw8ovFwmCjitPHEWkvwDAv0=,iv:O7WoBpry8BQm72kpuzTn1uDko8nAyQLbTmpmj/SiCGo=,tag:gq4eNsCXQMnK8zxMUtACHg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:dViCQuw4fasvg/qQxGVqmOI7PppnA0vWsa4VtcnirDNH+ZaAFRTDvSSKe4nNq/fai9GZFGdBVeVMLkBtxsUZ1yMMHoU8galufjfcdpiVznmq/IKg0DcoSe9FIX9FcZRjcBoPKUpSBwxB9iggreordTaaHeoSRKASibNQaJOukRsKqc6l792p/TvBRMpHe9tOpoNRs2Ts4oq8s0xf+f3d67q62TM=,iv:cF3bFSwVmp7EOEx7BQahEBsXMI51aB/eZ71GJIkoz18=,tag:Y3sWKK0Yy0B/mdAy1mQPRQ==,type:str]
    BIFROST_VK_LYCEUM: ENC[AES256_GCM,data:5mFB+dRAi8dbynC0JwpMQHvXJPBxX4wl4Wi6MARyk3+54h6rAjMSHA4BSS9VyOz46go=,iv:cx4380vnWB4O7qNaPy3Zq7oKtpVQW2OJ93qSIK+YJtY=,tag:Bzl3OrpxeqBV20NJT52WsQ==,type:str]
    LYCEUM_API_KEY: ENC[AES256_GCM,data:S8JRejfxj8IZnJDyFi2Jdda6TnTdp2e7KgNXmhMYc0whmWSps0BjJkd8IlhfEldUX4optHv1f+KdIEXk4M22RmfIUA==,iv:I89o/37dvER30EfT77891jG+6BWaQexRodLnvT8aqW0=,tag:nSsbpH5X8QpTxlsaWHotPg==,type:str]
    BIFROST_VK_EVAL: ENC[AES256_GCM,data:gH6D+JwiMF6WkoNglf2Xl/84NdvTsWNiBb8F2DlN3XB3SwGxxGRrIYMtKFGpL6MhWyIN,iv:jvNvTCVGcE/E9gCOhUl4PaVM9IyJJaGXYtIIUlXXYNY=,tag:YyOvS2XIMar91n6LAUE3HA==,type:str]
    BIFROST_VK_PAPERLESS: ENC[AES256_GCM,data:veczpoC2/8Jbelf5MboTdYJl6Z6Z65Paa7zLFcxJvISDIz/uqU55oYcEN9rICufwRr1t,iv:xuoIN2f4LgY49u8cQXvRUUjf7mntkhdfh9tmVDqrz/0=,tag:DaxJopJcj64b1aY4PJssmQ==,type:str]
    BIFROST_VK_ZETTELROBBE: ENC[AES256_GCM,data:GsvCS3W6OSgmfYyJUrWP/T6wTvEWXJMr5PYezB6d2pUThl7nJJum74Xgi2E8w4Mniw==,iv:JhuNgmCPT+35+JRuo/wIdTHwlE5yu+zPa0tFdt92Q7g=,tag:vBi+rT0QY9AfBUEKOEUopA==,type:str]
    BIFROST_VK_TENSORX: ENC[AES256_GCM,data:0YrRYi0Xcs7Iaur0WSyV3Pn6VTZ5+M75ptBcppH6P12Izn2kVZPkOlqpAqTV68UjBg==,iv:FESEjd/GwB1VxdEm3XgDKVj4uEuM4pYzTWYlgThwS9Y=,tag:8enPSYMzOmx0pFbTqZVI7Q==,type:str]
    TENSORX_API_KEY: ENC[AES256_GCM,data:Ak70h/8HzjgDmycyy7eridJiI7xqfWD/xQ==,iv:/ZO9il2fEjczEb0zcsMBGusKpvhN9vFCmbTDB4a3Ykk=,tag:nrolPGDTwxwa5SBEg0Robw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxM1UwZWxnTngzWDNWYjc1
            NzZYWHpiSWZhVlBrY2tmdzY2a2pVT24xaTNJCms2d2o0OHFwTitLaEgyMFUrWDlm
            YndUNWo2OVRabU8yS1A5YW5hYmczZUUKLS0tIHRhcU5jU1pvSUpxQUxrWC83NnVo
            a0RvQkR5YytpTjg0V2xIRWg2ditPWWMK1QQHABPX+sm60WVRyLPCgHQzAfxhLBIa
            qqJ4wDFe+oRS1dPZT9EEKSEuO30tdEXJbwFkuaN7cLGZF0PNM741hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T19:52:48Z"
    mac: ENC[AES256_GCM,data:KTVkqJbMMohOYWlMahnkc5OgA+7eY0i9px38vPrtVgMS3+BvYpSZWKszBtHYhaZ3q7d21o9mYlkYzqIDZQQKI3iehnoH4vTFjkkehu9NF0oBescDn+qa2ZO5oWuuQsEcg60ZI6s5GQrdv3fsOsapjhdkSADOGNNVXYX+TEWRgwE=,iv:2jVihVPjMN8avxjB1SBc1QMmXFHX2VLkogbqxVOlXdc=,tag:5lVgJ7TuUp3oywFvvtNp1A==,type:str]
    version: 3.13.2
