apiVersion: v1
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:sIMA2H90/X0E5q9OFkMxWQsxXYTX8WxaZDCHofQfJ68a0CcTWHjF8EADoiK8ggFE65Gn3U+N+bWvSrJe9Fsb/+SyHBKeUDpExdxnqZnftGWOKp5Qkva9ZRbXCt3S/eBKC/isBYoS1gluWZHGM0xKbs/FhXCVwKTf8QpOtZ/7gnlXAA3u6jcCzoIBOj92gajGt1k7puovFwN+Xt8yX/tuKoK9FYCRwUOvGDfZhpJmo0erooB+caXhGewXjSC2hlr07k+9LXuEOhbZ,iv:vDJu7svXFlI32mqGzEe6/13GNCuK84Gi8V9vDEAb7/g=,tag:v48M5PHLMNoKz0o1qfgOig==,type:str]
kind: Secret
metadata:
    name: random-gif
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwVTNMZ05LUlhrK3BBRVgv
            OWJmRjlIUm9ROFN4OVMxREJGMGFnMVlTSGo0CmtiTTBzOTlKY1NTRGJjVngwRzc1
            R3NxdWR6SFBtS0ZuVXlSS0h1ckFWUlUKLS0tIENyZG1nSks0N2s0RThlN0RRZnZV
            em54OW4rTmRKREl1ekNjZ0prdlgrM3cKa2L1vza1PIykmwgIR2hJ27XZ+4439Mqp
            zSpQZxZz30IJiUZnwTujgfpFbyLxaXgstQnq8wUkmb162Vrv2R8Kkg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T21:57:36Z"
    mac: ENC[AES256_GCM,data:YIRfUSMXa7v5SkHyMM7R6xsmVDV2aqrULdPKqM3tp1Qe1FdFKDNcBsUIhUnNedqGlnl9IFUDgGoo4i+wRTkzzrBjQEMYqK3z17IqThpi6stz1bXk1Ysfvn3aKgl+EuUs4sLCUsu60uvHm6sECCsKdVmLemGP8gOXXEohs2J2f7M=,iv:vB7dZpttKR3dFYaa9vtEaegkQERmTTGzdgtqUyWB28Y=,tag:LEua7d8NGpYwCsJgHhqUvA==,type:str]
    version: 3.13.2
