apiVersion: v1
kind: Secret
metadata:
    name: firecrawl-values
    namespace: firecrawl
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Q6jOtsg97OOg4MYO7cWM3CZbJSExZUUBI1vpdOYgMx6RdvoNQsPwtuWY2+RRkRJErBKUrNIqNAUpZ54oi8GpvQ==,iv:o/1Y2h7Kjorbc3C5u88aD4c1/Wvn8s9x/Gpy4uT0zW4=,tag:ihrB2c2C/Ufd6b/5ELydjw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVCtsV0FTYjYrMXRGNVV4
            NWRjdWhITWE4Q2lTU01sckl5bmFEVDBDZnlvCjI0NHBUQys0aU4waW83cUFzRS81
            RUIrSFhWZzZjNmJORzJpVEMzZ09kbkUKLS0tIDltODNYdG1LRnlMeUFxZm9uUFVS
            TDZsWHJZalVXMit5SndsZ2I1WkJITnMKOXU1o1BrXH3phe+UMHdNNSDqZTCpy/Ct
            7eouh+dDjzzkjwCfVRzp7A9iYeWU87BEk2LKpyFzJFjM5o0bYaMgJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T13:51:11Z"
    mac: ENC[AES256_GCM,data:uD7wErj3kvNZTD266+DOQbY8u7Hpu1x3wbn29Vii7BTSW2sT/7ld45gCK0Bcrc4Aj2TRlGn3P/FG3s5K6O8Fd6f3b1t16EDkSInCsCBXmfRhHUPHLupJe94V3/8wFdc+cQK/U+81drqIvDwlBNiXS5Fylwg6I+ef3DCRFUwF4r4=,iv:IocOOFPZdmL9CzsdaYhUlJE92LLgNviBvABeFaJQQTk=,tag:DZTmT/s6O5SszuS8OsnheA==,type:str]
    version: 3.13.2
