apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.sops.yaml
  - helm-release.yaml
  - ingress-internal.yaml
  - blueprint-external.yaml
  - blueprint-outpost.yaml
  - blueprint-identity.sops.yaml
