apiVersion: v1
kind: Secret
metadata:
    name: notgroschen-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:2FhcK3CWjNDxfGyfSrgCQn8qod/cAijOlQl01X4dzm1LhFCFdsO/xixjVTSZ0yG7rbLqzvRzooWBPUyznit8rReZQ6MpqfDA5aA6ic9y3sQSu8KfkgmF/ktivAiFqcW3pPgVb6HAXW4walRSmybmGoXUGkJN4mElmX/kkaP1Zf/wvJSsuic=,iv:HhOfeGMrfY1b1scopzuqZsPGKRNdNB0InquKvMlOGQg=,tag:BlkWu/ASXbMKlUsRfHPFww==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:qF6jBCiEEP2rQJJvoGLqgbr0PjxQ02FB8Bj9UaDSo+VvzAoud1rtgUMChHqIcOAu9FT4YlbBc5KgexXkh1uEsR5+gq3FPqMFDRZmMVkWw+P0QSGN8ff+/LNJvgMX3XVq0/vvqS8/rj06Q7wFrG250pdm9Zn5h7awRZwwi+PtdI8=,iv:ke07z7B5i/7f294X3/pDoAdwGq58+uZ+iPfsvGppvYw=,tag:KJ6TWixUEQWfMuKiJVTTwA==,type:str]
    INGEST_TOKEN: ENC[AES256_GCM,data:SVUJ0Z++MNmeF3WCMSesFlVdx2YlR1aGjdYMbiM+dT6si22WukmVRqleqMd7+qn914h6O4v3+NviwtV46w77Rw==,iv:8mYJjeTlR/H3w4DAzRT0eLqR6LX6bW4Ix4EQsJW4fcg=,tag:R3G2qMhNoqJGs+WQya8RRg==,type:str]
    LLM_BASE_URL: ENC[AES256_GCM,data:iRM0f6PL5CFhaRsQBYDnzvPe9RSPOUyMj8rdaQbeJGGT3POsJ3yX5NAAhrN8MBzI,iv:G2livsdcunAIApMoHmyePY1MZgaGJJULulD6sVMKFIQ=,tag:P4siHUC8aGCSbZa9ppR1pQ==,type:str]
    LLM_API_KEY: ENC[AES256_GCM,data:o3asgI6UWGgeWDf+KVfW6W5xSJ7b1ABd8pb7AcZzog5XSeiNjckGJdOmUWuf+KfSzlg=,iv:cUce6UMGgOmn+p7ErxO/bJw2GelCn5x09IL6RJDsHQc=,tag:N8+9CjdOciZOmq1eoAv1aw==,type:str]
    LLM_MODEL: ENC[AES256_GCM,data:UhzqRUjgfDbz/9e+3GPzqpeKRp1LDkCL76vo9qgilNZmG4XLWhGTRkc=,iv:Ai1JdjZchLsjeC2jQ1QbXDprwyRpT3Cx6HCHuyKr2JI=,tag:hINxxHE/feAFJtptu2D97w==,type:str]
    SOLID_QUEUE_IN_PUMA: ENC[AES256_GCM,data:iiV7ww==,iv:/PssJCphuslv8JOr3zZXJln/IqmQlsKZ0FHG5qRJgbs=,tag:VqCgXzbNVYnKVLE9Wp6y+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZnpGaEwwaTFScEdnSGVY
            UVFTQ2EwMTdmUVFxRmFTNUZYclJ1REdvNzA0CkVmbWtkYUZnVStmeVNiTENTNkdW
            UFhLejNrZlZsMEhUTTg1UVVDLzdCMWcKLS0tIEVhQTNkMmZ5VWExdHFtY3BOMWl0
            Um1RRDNYZU8ydFVxU05OTzQ2ai8wYXMKO74zEEluXq8ETlhSD/H6GuH4jv5zKgyn
            +hyCkQUuIKkl0Ex5PQT8Irrl78lAbM8+Sd/cqPHXrw0lpgBMEOCV4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T20:18:20Z"
    mac: ENC[AES256_GCM,data:q0T57UaxEZYtremVuNZtx+v7W/eIhpGhqmOKTyYYLnk5A3YaWEiMFeQpJzze031sAqflEeZEcbjbLa/lbGFH8KYG7YAvVLqgGUTIT57b2pLR2sFDT2GnLAMT7/icCRoTqPy5CkM9eDSnNtyyWTbedS7jC+5s6eEigguaWyjwI4w=,iv:USHcw633CwxfsNPa8mjm9o94GNaMoXqntro6f9Xu0x4=,tag:BnvZQgt9e6jB8cNMN9UVqQ==,type:str]
    version: 3.13.2
