---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-glitchtip
  namespace: default
data:
  glitchtip.yaml: |
    version: 1
    metadata:
      name: Glitchtip (gitops)
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_providers_oauth2.oauth2provider
        state: present
        identifiers:
          name: Provider for Glitchtip
        attrs:
          access_code_validity: minutes=1
          access_token_validity: minutes=5
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          client_id: rKdVK3lLUCePLx1bD8hYvKhDMZ1pYVWMa2XdVreC
          client_type: confidential
          grant_types:
            - authorization_code
            - hybrid
            - implicit
            - client_credentials
            - password
            - urn:ietf:params:oauth:grant-type:device_code
            - refresh_token
          include_claims_in_id_token: true
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          issuer_mode: per_provider
          logout_method: backchannel
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''offline_access''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''openid''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''email''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''profile''']]
          redirect_uris:
            - matching_mode: strict
              redirect_uri_type: authorization
              url: https://glitchtip.${SECRET_LAB_DOMAIN}/auth/authentik
            - matching_mode: strict
              redirect_uri_type: authorization
              url: https://glitchtip.${SECRET_LAB_DOMAIN}/auth/openid_connect
          refresh_token_threshold: seconds=0
          refresh_token_validity: days=30
          signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
          sub_mode: hashed_user_id
      - model: authentik_core.application
        state: present
        identifiers:
          slug: glitchtip
        attrs:
          meta_hide: false
          name: Glitchtip
          open_in_new_tab: false
          policy_engine_mode: any
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for Glitchtip]]
      - model: authentik_policies.policybinding
        state: present
        identifiers:
          target: !Find [authentik_core.application, [slug, glitchtip]]
          order: 0
          user: !Find [authentik_core.user, [username, yoyostile]]
        attrs:
          enabled: true
          negate: false
          failure_result: false
          timeout: 30
