apiVersion: v1
kind: Secret
metadata:
    name: glitchtip-secret
    namespace: default
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:D06G+hc9leuKVraoSav516yoJD7WZ4+9lm+3ifyNb7sc33f768HV+0XOKBE=,iv:Jdge7/FGc8ccVDGBvAIt+6kkAJUcoMwl7RY9imDXkAg=,tag:Xhkqyh6hj/j42cPITavAng==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:jYhgH1gFs6ZKLFyYx52S9GmNUOVlgQ46R8RqDjp7InqCDXC6FXo791Qw3l4lb8RQCTSq7AURpRR3OAYRcoA/tTWGUZbwCO2ld0SyaWpegUTII90TsGFrrMPjwKM=,iv:t60VIqV/Z4Jcgew6cdmyojai4iHCEfsMkVKCEQcfsK4=,tag:luFeFRlMeqI4/f40WhPOlg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:LDFGZRnrHjKUuCTQXRaMYWNelivVuEwGEscA3XPAJF+btA5RV8AVMYVrdXj0izupfPI4sLMEPMa759NkMS9t,iv:IERaLbXwnsMS8/gGnoU86AHZgRQDcNdxJUsLHRGiwQU=,tag:MnobUzY/MrANpvj5Rkf0GA==,type:str]
    EMAIL_URL: ENC[AES256_GCM,data:TTxRqRt5iqqL316gCfEKFdov2oc1XYT4jL/xqVvKJoTZcrtzWWrN83i5FPWe+F7+3A==,iv:ZElH6UXk+XVD49FsAIXaJMEM3npYkPTV4P5NvTd4x7w=,tag:8+So3bQb478XfNKVxLly0Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:WEkaCzVz5QigP/qv5O3dhSM+G1sQNLUPeQ==,iv:Wcoaz+6OrYA6g9RI/4NsE4xAbKrGTIYrdtOwKT3ljW0=,tag:i/KmUfV6DFiYyG106e3fdA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9l+VfxhgW4/OusaBPQ6vcjQGwwa8j3lCX/B8lG4+sg==,iv:jeULZp6pTmE3sd/WhRq/x8QlBcWiTub/+94AvfRjzCE=,tag:NC+/UfYd4HZaQ1PeaF52jg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWVpxSjB5QjFQRnBHc3dm
            SGFEZTJBSlA5SkdOcVdMdDJweTFKaVJhNEcwCmF6eDJtS29JT01RcjV2anlrVnFM
            c3pUb083T3Y5ampNcUVFdlAvblpNcjAKLS0tIDRVSkhTbyt4Zk9zZUczTk9ieFFB
            R0NhWGloVm9ZUGdKTk1hY1ZtUlBwenMK2HXqku8gATJvDqKq/OAZ7ntHUNP8Rc4n
            lrFwYVz6N43y6k+9vJdx1xuKgxaz7FOG9y2vKILHVTXE86lf1Dci9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T21:35:55Z"
    mac: ENC[AES256_GCM,data:O0pInnzVuQfz9DPi/2GnSIxl5VS2XdXfAdkgKOtCJ4rbM7QvSrBvMPWDRAM3uYBfxBXuxKq4aOx3ngV49C6pfq3or++npZ4JcXrWms03tFFPXriaUJOVG+/mea+Y7s2Iqv9dtFyX9/ETHWIl39y6wJDN953qa26Xsul2yEgjThc=,iv:GvUC4hDJalxrLZb5HkwAO5F8M3hiZgZAVVqd0jusfTU=,tag:QYZmSHQ/iQuKD+gC6wmpgQ==,type:str]
    version: 3.13.2
