apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unifi-poller
  name: unifi-poller
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-poller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-poller
    spec:
      containers:
        - name: unifi-poller
          image: ghcr.io/unpoller/unpoller:v4.0.1
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: unifi-poller
          env:
            - name: UP_UNIFI_DEFAULT_SAVE_DPI
              value: "true"
            - name: UP_INFLUXDB_DISABLE
              value: "true"
            - name: UP_POLLER_DEBUG
              value: "false"
            - name: UP_UNIFI_DYNAMIC
              value: "false"
            - name: UP_PROMETHEUS_HTTP_LISTEN
              value: 0.0.0.0:9130
            - name: UP_PROMETHEUS_NAMESPACE
              value: unpoller
          # Sized from 30 days of observed usage.
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 96Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
