apiVersion: v1
data:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:Lf5Pza12xf3edlrw,iv:IiyYNO9qPHEtF/z2D18RKPqDdA0OVlc6JpKHkEfc40o=,tag:W/u4+VwiXctBeG4MUJsrQw==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:iu0mGHnj0u1Rpd69ZfFhgXqG/xUGjK7gWLdorw==,iv:ShC0zChEqNjyxUBWfqKMcV4GvXCh6F4XDzl057rOyC4=,tag:2MKmFAEu8YT4YDqZaTob5g==,type:str]
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:mdGtIzP8/fLdmb8hPLzIAMmI4L7t6SzmIMYfyf3Jd/f2oKNQN1yAZ/QbA6E=,iv:KcIM0wuo7yOmdCOzPWc16rzqY3Reha9OcHMm1GjJvIQ=,tag:suGLwAk7Du0JjK0ulfmtzg==,type:str]
kind: Secret
metadata:
    name: unifi-poller
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3h3SkcyMHBFaExhc2JO
            MnNPZGNOWkdmOCtYTUd0OVoyRDNTU0dpYzJNClZnbnc3MzRRakg0cjRkSktyV0Zm
            NHpsL2VTdHNXS0hwSXArYmVaNUR0Q1UKLS0tIExSeks4MEVFSFlNTmUwdDc4RFYr
            d09rVHhlQ1djWmxtTllHZ3pWNXI1ZG8KvhysjK+2gKGBkai+5A4qYh2VviFIyWLr
            K1LGtPvvdHQVj1BAN5TzGeRxkJtfe28+J2IMDootloOzUwKHuejkww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T18:57:51Z"
    mac: ENC[AES256_GCM,data:VYoCocfqduiLuN+uSoD8n3Fqbh5jjHwqi3uiiAxVBhNLDjwa7cNLMoLEKeRznFwk/whvWB0PbeB8o4PUsWbPLKKaHO2bMq5POjdkvk2+bMmEb8GeLvDDvfWhyz7kLscbvsZNS5Hss6ATkUc93oIN7ZUjSapnw5+b9RbuKYZ90iE=,iv:roeKfYkQdX83R7cmBMPsyxZyHHk+JYb9kAf3m+DugS0=,tag:FSbRwikf4FREyp9IDom/1Q==,type:str]
    version: 3.7.2
