apiVersion: v1
data:
    UP_UNIFI_DEFAULT_USER: ENC[AES256_GCM,data:duz3xARNPE4=,iv:8n+tvhd/kbpJjG6ettC8dtxBz3056uK3HltxfF+420c=,tag:6Vo5O5qax+tr23qQ3Aq+JQ==,type:str]
    UP_UNIFI_DEFAULT_PASS: ENC[AES256_GCM,data:+K6uESlIhQE9dfxtjbxctVVlr0sTroNtlmQY5UTRHnW4EnutBk0Nxv5piHyfJmxm,iv:Coji+3dGwqLfCPaxWpoZS6ieZhKGvO8CAyXBmS+Vqhg=,tag:s1Jnn76OihMSoigD5mMmKQ==,type:str]
    UP_UNIFI_DEFAULT_URL: ENC[AES256_GCM,data:mdGtIzP8/fLdmb8hPLzIAMmI4L7t6SzmIMYfyf3Jd/f2oKNQN1yAZ/QbA6E=,iv:KcIM0wuo7yOmdCOzPWc16rzqY3Reha9OcHMm1GjJvIQ=,tag:suGLwAk7Du0JjK0ulfmtzg==,type:str]
kind: Secret
metadata:
    name: unifi-poller
    namespace: monitoring
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ3h3SkcyMHBFaExhc2JO
            MnNPZGNOWkdmOCtYTUd0OVoyRDNTU0dpYzJNClZnbnc3MzRRakg0cjRkSktyV0Zm
            NHpsL2VTdHNXS0hwSXArYmVaNUR0Q1UKLS0tIExSeks4MEVFSFlNTmUwdDc4RFYr
            d09rVHhlQ1djWmxtTllHZ3pWNXI1ZG8KvhysjK+2gKGBkai+5A4qYh2VviFIyWLr
            K1LGtPvvdHQVj1BAN5TzGeRxkJtfe28+J2IMDootloOzUwKHuejkww==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-05T18:48:18Z"
    mac: ENC[AES256_GCM,data:FXVfyXnlcQdH/vZgnbrJ/Su8v1N9EO0Hh9XdoEvl5raLSK+XGM7o/OjUnk7tEhhZxCIKezkxxhGGnndCBhxVcXGlGsEiXeo1crvTZk4Y2g9TYOIV+IBsQ4ucvlYE5Zg98r675FNWZGCePUwm/672O7xOUzMugW38R3iXLIRJy7k=,iv:PijC80RN5aHHC7VyYMgQvw/1ARSaMjZVYnKQN2hQ9Js=,tag:sx08cI51yPc9fMnb9axVYA==,type:str]
    version: 3.7.2
