---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-zigbee2mqtt
  namespace: default
data:
  zigbee2mqtt.yaml: |
    version: 1
    metadata:
      name: Zigbee2mqtt (gitops)
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          name: Provider for Zigbee2mqtt
        attrs:
          access_token_validity: hours=24
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          basic_auth_enabled: false
          external_host: https://z2m.${SECRET_LAB_DOMAIN}/
          intercept_header_auth: true
          internal_host: http://zigbee2mqtt.default:8080
          internal_host_ssl_validation: true
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          mode: forward_single
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: Proxy outpost']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: Application Entitlements']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''openid''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''email''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''profile''']]
          refresh_token_validity: days=30
      - model: authentik_core.application
        state: present
        identifiers:
          slug: zigbee2mqtt
        attrs:
          meta_hide: false
          name: Zigbee2mqtt
          open_in_new_tab: false
          policy_engine_mode: any
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, Provider for Zigbee2mqtt]]
      - model: authentik_policies.policybinding
        state: present
        identifiers:
          target: !Find [authentik_core.application, [slug, zigbee2mqtt]]
          order: 1
          user: !Find [authentik_core.user, [username, yoyostile]]
        attrs:
          enabled: true
          negate: false
          failure_result: false
          timeout: 30
