{
 "title": "Main",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "sn0w.lan.${SECRET_LAB_DOMAIN}:9100"
   }
  ]
 },
 "panels": [
  {
   "title": "Inzidenz Köln",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_unit_u0x200b{entity=\"sensor.inzidenz_rki\"}"
    }
   ]
  },
  {
   "title": "WiFi Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(unifipoller_client_uptime_seconds{essid=~\"Saunaclub Paradies|Saunaclub Paradies Guest\"}) by (name))"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "auto" ], "type": "time" }
     ],
     "measurement": "ups_load.value",
     "query": "from(bucket: \"sn0w\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_load.value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 * 390.0 }))\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100*390" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost / Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "ups_load.value",
     "query": "from(bucket: \"sn0w\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_load.value\")\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 * 390.0 * 24.0 * 30.0 * 0.001 * 0.2442 }))\n  |> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/100*390*24*30*0.001*0.2442" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "sn0w: Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=\"$server\"} "
    }
   ]
  },
  {
   "title": "sn0w: Available Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$server\"})"
    }
   ]
  },
  {
   "title": "st0rage: Free Space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{device='stor01/enc',instance='$server'})"
    }
   ]
  },
  {
   "title": "st0rage: Total Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device='stor01/enc',instance='$server'}"
    }
   ]
  },
  {
   "title": "sn0w: CPU Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance='$server'}",
     "legendFormat": "CPU {{cpu}}"
    },
    {
     "expr": "node_cpu_frequency_hertz{instance='$server'} ",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "sn0w: Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "repeat": "node",
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'$server',device=~\"bond0|vmbr0|vmbr1\"}[2m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'$server',device=~\"bond0|vmbr0|vmbr1\"}[2m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  },
  {
   "title": "WAN Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(unifipoller_device_wan_receive_bytes_total{name=\"USG\"}[2m])*8",
     "legendFormat": "WAN in"
    },
    {
     "expr": "-rate(unifipoller_device_wan_transmit_bytes_total{name=\"USG\"}[2m])*8",
     "legendFormat": "WAN out"
    }
   ]
  },
  {
   "title": "sn0w: Detailed CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu_seconds_total{instance=\"$server\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\", instance=\"$server\"})) or sum(irate(node_cpu_seconds_total{instance=\"$server\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\",instance=\"$server\"}))\n",
     "legendFormat": "{{ mode }}",
     "prometheusLink": "/api/datasources/proxy/1/graph#%5B%7B%22expr%22%3A%22sum(rate(node_cpu%7Balias%3D%5C%22%24host%5C%22%7D%5B%24interval%5D))%20by%20(mode)%20*%20100%22%2C%22range_input%22%3A%223600s%22%2C%22end_input%22%3A%222015-10-22%2015%3A27%22%2C%22step_input%22%3A%22%22%2C%22stacked%22%3Atrue%2C%22tab%22%3A0%7D%5D"
    }
   ]
  },
  {
   "title": "WAN Speedtest",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "download_speed_bps{job=\"speedtest\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "-upload_speed_bps{job=\"speedtest\"}",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "sn0w: Load Avg.",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "repeat": "node",
   "yaxes": [
    { "format": "short", "label": "Load Avg." }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "sn0w: Temperatures",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "query": "from(bucket: \"sn0w\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ipmi_sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"unit\"] == \"degrees_c\" or r[\"unit\"] == \"rpm\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.name }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "rpm" }
     ]
    },
    {
     "alias": "$tag_feature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "feature" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "temp_input" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "temp_input", "operator": ">", "value": "0" },
      { "condition": "AND", "key": "feature", "operator": "!~", "value": "/^temp/" }
     ]
    },
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "degrees_c" }
     ]
    }
   ]
  },
  {
   "title": "APCUPSD Stromverbrauch",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ups_load.value",
     "query": "from(bucket: \"sn0w\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> aggregateWindow(every: 1m, fn: mean)\n  |> filter(fn: (r) =>\n    r._measurement == \"ups_load.value\"\n  )\n  |> map(fn: (r) => ({ r with _value: r._value / 100.0 * 390.0 }))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100 * 390" ], "type": "math" },
       { "params": [ "Power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "sn0w: Disk Utilization per Device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "repeat": "node",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=~\"$server\"}[5m])*100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "UPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "volt", "label": "Voltage" }
   ],
   "targets": [
    {
     "alias": "$0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^ups/",
     "query": "from(bucket: \"sn0w\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ups_battery_charge.value\" or r[\"_measurement\"] == \"ups_battery_volt.value\" or r[\"_measurement\"] == \"ups_line_volt.value\" or r[\"_measurement\"] == \"ups_load.value\")\n  |> map(fn: (r) => ({ _value:r._value, _time: r._time, _field: r._measurement }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FHEM: Temperaturen",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    {
     "alias": "Küche $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "room" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "max",
     "query": "from(bucket: \"fhem\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail\" and (r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"desired_temperature\"))\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r._field + \" \" + r.path }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n",
     "select": [
      [
       { "params": [ "valveposition" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Öffnung" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "room", "operator": "=~", "value": "/^MAX_0b196b/" }
     ]
    },
    {
     "query": "from(bucket: \"fhem\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tail\" and r[\"_field\"] == \"valveposition\")\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r._field + \" \" + r.path }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n\n"
    }
   ]
  },
  {
   "title": "Klima",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Schlafzimmer $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "from(bucket: \"fhem\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"valveposition\" or r[\"_field\"] == \"pressure\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Humidity" ], "type": "alias" }
      ],
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Temperature" ], "type": "alias" }
      ],
      [
       { "params": [ "pressure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Pressure" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "zigbee2mqtt/0x00158d0004657fb8" }
     ]
    }
   ]
  },
  {
   "title": "Weather Cologne",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    { "expr": "darksky_apparent_temperature", "legendFormat": "Apparent Temperature" },
    { "expr": "darksky_temperature", "legendFormat": "Temperature" },
    { "expr": "darksky_humidity", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Rheinpegel Köln",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "rheinpegel_measurement{location='KÖLN'} / 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Höhe",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "expr": "rheinpegel_trend{location='KÖLN'}",
     "legendFormat": "Trend"
    }
   ]
  }
 ]
}
{
 "title": "TheThingsNetwork",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RSSI gw01",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"metadata_gateways_0_rssi\") FROM \"fhem\"..\"mqtt_consumer\" WHERE (\"host\" = 'fhem') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "metadata_gateways_0_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "fhem" }
     ]
    },
    {
     "alias": "RSSI gw02",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT last(\"metadata_gateways_1_rssi\") FROM \"fhem\"..\"mqtt_consumer\" WHERE (\"host\" = 'fhem') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "metadata_gateways_1_rssi" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "fhem" }
     ]
    }
   ]
  },
  {
   "title": "Post",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "measurement": "mqtt_consumer",
     "query": "SELECT \"payload_fields_mail\" FROM \"fhem\"..\"mqtt_consumer\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "payload_fields_mail" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    {
     "alias": "Battery Voltage",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt_consumer",
     "query": "SELECT mean(\"payload_fields_voltage\") FROM \"fhem\"..\"mqtt_consumer\" WHERE $timeFilter GROUP BY time(5m) fill(previous)",
     "select": [
      [
       { "params": [ "payload_fields_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}