apiVersion: v1
kind: Secret
metadata:
    name: github-webhook
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:cbx14ZiiZd/Gy/zQ+GPZ6lL0J3oR5Wkut14Jclpx4ufIaL6i8tRUYA==,iv:iQC7V2laMILc21WITZ57lRCPiDA+V5vqZLTzer3cRCA=,tag:2o+6V0Fs4ppp0bsnQ1DwyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NmcyczU0SFJzU1VIZGlz
            QlhYMFFxK2hxWnlXNjFKSXc2VS94TWtEcVZNCncrdHltcDEzU2NqNHpPc3kxSEFT
            YTlvM2Q5c0ptSGpPTWF0VHRTRk1RLzQKLS0tIFI0N3V1Z21lZ0JqcENqZnpMMW9D
            clRiYmpwVEdxYnRNa0FHNFVkSlNpeXcKgpyGcxqHTw2E5+kyYrvk6BGHseo7j/Uu
            3li2tganBepRZHyYLGR/Tgt+Cixz/yXap0G8ianzVkKDLZHqWHl5AA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-19T12:54:58Z"
    mac: ENC[AES256_GCM,data:dE4YfQq3A2moV5yDAD6pnaaB+cJHut/TPSh6uWKLgSFiiQxW4ka8PzigmfgoabcJsjvZVwocP8tTx7RZwKFpmLqNnfKCL5fqdU7T2KrPsOLAo8BcVuMiMXEE6OxJ1VbimdaYyQj+OwNjbkgtEN2zuMaJgTNhSbXli7HQ83IQNqw=,iv:wxDjgopxRWzacLSXwpRHhBv4bpuqYTIph97ivNN8Sbo=,tag:dVr8+zSYZbJv4qqIKt0fQQ==,type:str]
    version: 3.13.2
