apiVersion: v1
kind: Secret
metadata:
    name: reimbursat0r-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jNTH+3cybCzcxk1kdWWnk8SfsnnZ7eH6SeMlWJcP52+9dpeGcJaWCGuxdbTlKCQf1LTTyj5JCZxOOwVcLqUjbHpjT+Q3,iv:YHCCUho+jVqdkfuCzdXelxTa6ilS9WG5747BTrziahA=,tag:xiZeo5YYDger1KjheCGDuQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:dGcyuXso+LJXNnrVbMlsgj44N49IveQnTGj9o3dZ+GMTfqxI90XohdcM6dLKCnB98gyy9EPThrNsAIiaP+QFoIkhPLCDn86IzsOvfXTmT1SyxbZf9EjQbG8Ui7npyAJbcQTZujc/9BP4frp4+lM=,iv:i0nvMatF5M2Zq2vEPVVseRg+9GKkg2lQbXqXYlxUlmA=,tag:JsQZ9bCzqZf0KlpeO+KTPw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:vkp/+LzVqZ+2RHsKuPZj9pgGoxII1DV6ecnpwwAnHpVLCSykTZrPrP2ReJ0TTulTlNmr+pVRR1tWWd3eBL+FZXU42nX35CVOXf+177TmqdpNRyOOno6EJcKD2Q34K/2n0+X/RAOnvuTa2dkVHIqMcfdGr1SJn8JKj1OHCuBKft8=,iv:gQAb/A1tdto4BXdKDA3Keoghv9m5J0lNcSIqY+NaFak=,tag:1MgVuow/j17uY8AtXxvmJQ==,type:str]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:n/mA0hGJbKUHCZ6HUcKWg2WcNC1qKMe1MkaD9OGZ3LduYRD6BKi0cg==,iv:ARGH1uHXEb6QX4pYbD70hVQx3IGTVYWS7Ku4XMj9kB8=,tag:l5vesJ9HIMuvjw1O0KF/YA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:kZs6fMkFe0thZtHNkm9Cp4DE4ceRlAxxdRT9wy6sVzsMLMEEgWxO7vlmFAxJgLNi8NXlfWD5MvXsya3VFiwdESiE01vZMqDE+awftSNvg9bxnVKl8wdtdgrTBesyKUObcloFl8sxnTOfVkmZ,iv:Ai+YfbgWbRSrU6Nd92qloCgj1Eb3VPXp6ChhAmCGFqA=,tag:jqVyCH5Bi3JRd3dqc9P+Dw==,type:str]
    BIFROST_VK_INVOICE: ENC[AES256_GCM,data:yI/fIt7VHsV6PYjQrHpflJv+PPzl1Ji7z9HTtYXHfpxs6AhYOd2A1F7cyhEm0uz/FVE=,iv:IoUP0oixrL9I4yqDPNz/Ajiwro5KVOGvMaoqNvsJDdU=,tag:Th8DOd3F3EJq/M8SX6g+2w==,type:str]
    BIFROST_VK_NOTICE: ENC[AES256_GCM,data:m9iew0MlpNoQoqh4tPCLrs9TlqBWwVJOtHmLOQisVIXLjX4nRWaBNzHC28ADlExVPaA=,iv:7qb2XT2AcyuxheWi97xl9QSSCBUmoEnrQuZIVKXk2EY=,tag:2SWBiFbZ27Vjnefaf7iBxQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZDhDOW1WZUZQcXVDN2FS
            dnZtTDlCRFBkWHBRbkkxNGZZZzQvNXNvVUI0CmhBdFhra2IrMU9wM2FkZ2FpcXNJ
            dVZ4bGlOc0dYSWRwZ0k3a1l5MlEzTlUKLS0tIEcyRFJSa1lndHY0ZjBLOVVDVlJU
            azVGS1lnaHFLZmx0eHplTEZMNFpyVEEK/UmGH21O+P9EX89jQd40na7JyyaeL/Xr
            ucuD8DR/19FvCued2HxVghIqufn77i27mEPGqumnBBeAyzZdFtVaHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T12:37:58Z"
    mac: ENC[AES256_GCM,data:P9P9+CSYgfgBfeblp/0Ab0ktB7HTW8T9TGa6r+LyhF+MJOHVDhDO8Yg+/bzrcrD0m6lqIlfPFAH1Esnvh0hOY2My0BtPgwLluL3OVYi5tuGgSUNPdGVaYXgp9uOtVbDr5hU5ZutkLK/s3UIwnYuqCT82tftWxpvElrvtNb6MNkE=,iv:dVUUcEA5x4uEXL87Ry2JHgAglJSjFJdaDx+4a/Rk/eM=,tag:mHEIxT3sLPKgWou/L156QA==,type:str]
    version: 3.11.0
