apiVersion: v1
kind: Secret
metadata:
    name: reimbursat0r-secrets
    namespace: default
type: Opaque
stringData:
    #ENC[AES256_GCM,data:jNTH+3cybCzcxk1kdWWnk8SfsnnZ7eH6SeMlWJcP52+9dpeGcJaWCGuxdbTlKCQf1LTTyj5JCZxOOwVcLqUjbHpjT+Q3,iv:YHCCUho+jVqdkfuCzdXelxTa6ilS9WG5747BTrziahA=,tag:xiZeo5YYDger1KjheCGDuQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:dGcyuXso+LJXNnrVbMlsgj44N49IveQnTGj9o3dZ+GMTfqxI90XohdcM6dLKCnB98gyy9EPThrNsAIiaP+QFoIkhPLCDn86IzsOvfXTmT1SyxbZf9EjQbG8Ui7npyAJbcQTZujc/9BP4frp4+lM=,iv:i0nvMatF5M2Zq2vEPVVseRg+9GKkg2lQbXqXYlxUlmA=,tag:JsQZ9bCzqZf0KlpeO+KTPw==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:vkp/+LzVqZ+2RHsKuPZj9pgGoxII1DV6ecnpwwAnHpVLCSykTZrPrP2ReJ0TTulTlNmr+pVRR1tWWd3eBL+FZXU42nX35CVOXf+177TmqdpNRyOOno6EJcKD2Q34K/2n0+X/RAOnvuTa2dkVHIqMcfdGr1SJn8JKj1OHCuBKft8=,iv:gQAb/A1tdto4BXdKDA3Keoghv9m5J0lNcSIqY+NaFak=,tag:1MgVuow/j17uY8AtXxvmJQ==,type:str]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:n/mA0hGJbKUHCZ6HUcKWg2WcNC1qKMe1MkaD9OGZ3LduYRD6BKi0cg==,iv:ARGH1uHXEb6QX4pYbD70hVQx3IGTVYWS7Ku4XMj9kB8=,tag:l5vesJ9HIMuvjw1O0KF/YA==,type:str]
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:kZs6fMkFe0thZtHNkm9Cp4DE4ceRlAxxdRT9wy6sVzsMLMEEgWxO7vlmFAxJgLNi8NXlfWD5MvXsya3VFiwdESiE01vZMqDE+awftSNvg9bxnVKl8wdtdgrTBesyKUObcloFl8sxnTOfVkmZ,iv:Ai+YfbgWbRSrU6Nd92qloCgj1Eb3VPXp6ChhAmCGFqA=,tag:jqVyCH5Bi3JRd3dqc9P+Dw==,type:str]
sops:
    age:
        - recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZDhDOW1WZUZQcXVDN2FS
            dnZtTDlCRFBkWHBRbkkxNGZZZzQvNXNvVUI0CmhBdFhra2IrMU9wM2FkZ2FpcXNJ
            dVZ4bGlOc0dYSWRwZ0k3a1l5MlEzTlUKLS0tIEcyRFJSa1lndHY0ZjBLOVVDVlJU
            azVGS1lnaHFLZmx0eHplTEZMNFpyVEEK/UmGH21O+P9EX89jQd40na7JyyaeL/Xr
            ucuD8DR/19FvCued2HxVghIqufn77i27mEPGqumnBBeAyzZdFtVaHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-24T07:50:40Z"
    mac: ENC[AES256_GCM,data:REjdR4IVhHjUfUbNC3hiJjwkJH9h846IGL7JTZawsEMt5AknbQvqqswlYJmlv9LLQQ8KnuqJZuH8nuJrgemUaLQ+rTNnFxMRD3cJWRkLkRI+/roxK9M2FwabeuCkBYapB7n2oGBumtBf/rPWWvOfdsr5Z7BWoM7l885St3Eag0U=,iv:zpmbEXrmR003lvoq7RRjhc0yQpwJVrGZkCnALMzIsp4=,tag:QVSZxxufXNmR28aEKgDX+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
