apiVersion: v1
kind: Secret
metadata:
    name: reimbursat0r-secrets
    namespace: default
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:6cDlCRoPwCKZ6OuQwJwwKf/VNBAd0fIFzXBcyZtsvCcxOkj226p4V6FzSFC3WtFMIXhXs4pfAKQZerGWYwVSQvQnF59ifsW5xGcLqQ42NKQoPAW4Mgme2g2m/0hpION0D2kZIRK1A7GE898eHAk=,iv:DH+t6PckqoFyIOuVfJMMlrrBRc9trlm3UoU6lt++URc=,tag:ZgdRZx85UbtRv8AfaK9AHA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:bxp1imsw+2aW7c1x1cVap63ihFh8t+JLH/SK8DW+1nUAabXI2bxlhgM05UZZRn2Bpcb6S45GxtihCrlf2fzUrjNxNKlINcAV176usx6k3zE01/UG+7Qq5e4LA+MqvLyFLw/+8KH3TUzevmMohgA7rtb45DwogSMhnUXPPq4isYE=,iv:HELUvc17I/W2ck/LTFuF2j089KBaYWBPpzb4iLaUOuU=,tag:ryJ5DW1hQyOIhJ+5GNAlDg==,type:str]
    PAPERLESS_TOKEN: ENC[AES256_GCM,data:eeDE4sLuYLkzZEhO9Fe2kIVpNM2MPTBQ+puU/TK3czvTa9OTw0PHJw==,iv:8/AWcztP/kBN9DquMxdTWtYofgc22MmKVrPzQp+q4JY=,tag:lY8OySTZwnq7ioVXuFM+mA==,type:str]
    BIFROST_VK_INVOICE: ENC[AES256_GCM,data:dzhZJv5v5w76c482Scyy312KDvaqoyScFGUSCHxc65Ks4S+lKM+BxwhyNr6N+oIc91M=,iv:uCsntpNiGGBOfo98fFuPgyZvE+oubjOyKKHp+Be2Z/8=,tag:ayx2IYpY4HZuv2Pw8qN1gA==,type:str]
    BIFROST_VK_NOTICE: ENC[AES256_GCM,data:Ckd+hY/W/7mkrlnhUzIclPCFqzB1CllsInNefyx7PffKeJklXFc0owtifisKOIROe1g=,iv:SXPU1BSxbxVc9MTxGbLTO31WivNJPbZI/ECsvVM3gCs=,tag:pWEgJWeNX4LjAO8oyM3kMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UDVhTDdGSlBpdHRKQ3N1
            UnpoS3FkN0I2cDkrK2NVWFdxenpyYUczOW5ZCkY5NTJwckpDTHdMb0NYMDQ3UlRW
            VW9weW1nZXVLVk8yNmJEcmtJcEdkdHcKLS0tIGdYbGlQMVAveU45UXYrSGx6MG8z
            TDZOb2ZkYU4vV1lVb1JZMzNYcS9lUE0K7BA/lgDqX7eEAIg2QA6GAckKJSY5bvLx
            bxWX8hj72WlDvjSElCwXxT/GyB1pRAd6t81XJKkiZuTZgIX+OS4JfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-30T18:48:51Z"
    mac: ENC[AES256_GCM,data:Njex0WB4VLoIVKlzYyovNGOEMeSUO2xhDjqkvI3cf/pbb0tkx5/x0KcD11j0A9zTPIxvSsMY0te0mJ4namSEG/D+2WNazxyCjwPuat4r0yAn9RrdPC73nbijhya29dJ1PqY13THlaKleCJUZSf2iI+rfGJ10/wZp0HiRNbbOlas=,iv:XM6ALYZyYeXK1E9LbQ7tjaucD1t0JmphR0HQoBnQK9w=,tag:9qIUh6QUB1LVdBbKEKMd8g==,type:str]
    version: 3.13.2
