{
 "title": "Main",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "pve01.lab.${SECRET_LAB_DOMAIN}:9100"
   }
  ]
 },
 "panels": [
  {
   "title": "Power Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_power_w{entity=\"sensor.innr_outlet_1_power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cost / Month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(hass_sensor_power_w{instance=\"hass.lab.${SECRET_LAB_DOMAIN}:8123\",entity=\"sensor.innr_outlet_1_power\"}[1d]) * 24 / 1000 * 30 * 0.30",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pve: CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_cpu_scaling_frequency_hertz{instance=~\"pve01.lab.${SECRET_LAB_DOMAIN}:9100|pve02.lab.${SECRET_LAB_DOMAIN}:9100|pve03.lab.${SECRET_LAB_DOMAIN}:9100|pvenas.lab.${SECRET_LAB_DOMAIN}:9100\"} / 4)",
     "legendFormat": "{{instance}} CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "PVE Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=~\"nvme_nvme0|platform_coretemp_0\"}",
     "legendFormat": "{{instance}} {{chip}} {{sensor}}"
    }
   ]
  },
  {
   "title": "sn0w: Load Avg.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "repeat": "node",
   "targets": [
    {
     "expr": "node_load1{instance=~\"pve01.lab.${SECRET_LAB_DOMAIN}:9100|pve02.lab.${SECRET_LAB_DOMAIN}:9100|pve03.lab.${SECRET_LAB_DOMAIN}:9100|pvenas.lab.${SECRET_LAB_DOMAIN}:9100\"}",
     "legendFormat": "{{instance}} Load 1m"
    },
    {
     "expr": "node_load5{instance=~\"pve01.lab.${SECRET_LAB_DOMAIN}:9100|pve02.lab.${SECRET_LAB_DOMAIN}:9100|pve03.lab.${SECRET_LAB_DOMAIN}:9100|pvenas.lab.${SECRET_LAB_DOMAIN}:9100\"}",
     "legendFormat": "{{instance}} Load 5m"
    },
    {
     "expr": "node_load15{instance=~\"pve01.lab.${SECRET_LAB_DOMAIN}:9100|pve02.lab.${SECRET_LAB_DOMAIN}:9100|pve03.lab.${SECRET_LAB_DOMAIN}:9100|pvenas.lab.${SECRET_LAB_DOMAIN}:9100\"}",
     "legendFormat": "{{instance}} Load 15m"
    }
   ]
  },
  {
   "title": "Klima",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius{entity=~\"sensor.0x00158d00051e0e66_temperature|sensor.0x00158d0004657fb8_temperature\"}",
     "legendFormat": "{{friendly_name}}"
    },
    { "expr": "hass_sensor_humidity_percent", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Raumtemperaturen",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "hass_sensor_temperature_celsius",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Leistung Steckdose",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(hass_sensor_power_w{entity=\"sensor.innr_outlet_1_power\"}[5m])\n\n",
     "legendFormat": "Leistung Steckdose"
    },
    {
     "expr": "min_over_time(hass_sensor_power_w{entity=\"sensor.innr_outlet_1_power\"}[5m])\n\n",
     "legendFormat": "Min. Leistung Steckdose"
    },
    {
     "expr": "max_over_time(hass_sensor_power_w{entity=\"sensor.innr_outlet_1_power\"}[5m])\n\n",
     "legendFormat": "Max Leistung Steckdose"
    }
   ]
  }
 ]
}