apiVersion: v1
kind: Secret
metadata:
    name: zettelrobbe-secrets
    namespace: default
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:4X2CMP7UJx/CjswviFwSTlxH+DMQ4fQ/nTDqV3yrxCxhrmnPTPWLMg==,iv:NwaZArFNyexyGXqO4cLAY0EoAzyU1C9/pdDdZUb1Y+4=,tag:UXFJHsPj16Stnm6Exzhm2w==,type:str]
    CUSTOM_API_KEY: ENC[AES256_GCM,data:6xs/Voqj2t9DEjuIURiNv0YOsdWvBppq91tg49zgDa0Rupt5eQO2KuB30EYXU7Bgkw==,iv:0PTx+xePgl6iSJBzvsaFWYPFc6maTzYkNvmK8FLwWs0=,tag:g7e8M9IM7cGzQRJRFFBdyg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:HMIRrAg69St9gWPrncSaEs1bFvCAWuHypRYB4PX1n+E6MMeK0mPaxIDHkYvaSbGuUPk5sjgiP5cCk0RIzDDV1Q==,iv:xZbRIOmi5t0ZPS8wv7Gfu7KgcWyZc/2uDce2VWTC+14=,tag:OAgUpCynMPh8vR8V9t3dRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxc2ZZOXFCZjFRQUgrc0tw
            M2Nnc0tGMlBIVFNxTWpsSUNOU2V2dnQzbXlZCitiVFJPYUZDV2p2bEE4dEM3b2JH
            T2RNbVIyVmUvYjN5SDFNS1RneU9PemMKLS0tIFNsZUhvN0RDWDl0UzlOand0S0lm
            YXhWdkZGc2h5NUdJSmR6VytHMVdzRDgKU+Fcm1FqjzLDTxpEAGEzi/+/7GN3VZEU
            MKbCx5wPagVpAh6Ly5NAPoh+n0nF2ot9N5jWR2OHvKpDuW7KYuwQJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T20:28:27Z"
    mac: ENC[AES256_GCM,data:Mt5v10RpAgeZXDO4T7SjCXVSFHZQhSHuFUtFsxQx250g66nLHi7J/ylzYSVdbt2VPElv8OpmEQEp+x9tlC6uIRI0CNZqYZuHIqT8fADEdC4cAeIwhME5maXFYRU9m694CMKa6ULbXOcZ3AKuxoTN/pYLOQaZQfXKFgGfRsdOINA=,iv:A2h6h6CXmVcCdTns5h5a2JpIoXFtA/LupzbO4DlAEnk=,tag:MI/ENnrQ/+pKJwU1plkVsQ==,type:str]
    version: 3.13.2
