apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-wg
    namespace: media
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:bzi8WSwmtrHcqj347nSETN/c7Pf92pm+yFD1rjpxzERCFzh1hzdNZj7FX75KmXGfzjDffNboPquGaPEshdKqDsTWgWl+CMCzVgRhc6g/izaCD7/qipkt6tdae083tcT5+M1eLwPVXC6+q4X94481aNyndQsmummeLRN9R5qaHlPVakSm+M6zpizRVy9d1NO5ucXQ/mBDjj9d/13I6e27d+WQa8mF3jXqzSdwf0YGdOK+8OulNU6Jam1T03+0jrHxCQCKEvJ+ubfIMBNMA8bXIee0Lvtgq9sdIFDBh2FURsO7dIUCTq96pVUwXrFYh5nO4u38/sZPmxRdrIP7Y0IB7DH1YT3pVrmw49gVHXWX/qm+tlywqxv6F8UWY087KMXLvUVWlayseW3bd1OVvVVpi4XPkI5WVsaOuGR70sJjwe0xVlAej0AMJS8SVXJ8NSZPoEvqmOt8jbLcSnYsClTqeAASqRREuWhM+2S/nvV5NYp0n9yFnOS6HdSDmbbfP8ZT0pwGIDKJGN1AC92RkWpHjy/KOl1ZKyvTVb/BkKGcKQHUIBi1IarsY/JRQ5XRR9yzIelhc20w1/6RoE0mrUiGg8d4b3kAwR2R2U48BeTh/2FX0GsbsyJCiJ7ciXntxIaMw9u+zUAMeZFULw+Dv7aEIs4OanM6ohuiDexkzOD+VM8OYbzxBQhovxDZLI73zUDxbJ0LV/YDtICWrk0Ns3ABNmNgaSnj32b9T1xIF4kdDGyepbnzTRTN+4dA7yavSaTvgy6rcgn0RU5qD8QChJpckVs5JrhSlMBjSdJQyeuGkbh7eJQ3TYWs0Q+wPk93jBq8Gv4ymoa9duPimHMkKQyFotKh4Siqdw8xiZ3rbdCcZ968qNFN3JYtN2GXQpuzC8lDnO7YnIGrF8HOaY41bsNn/HWP3ZXyHTM3QBaKuy0Smz7aY/kbqZb1WErkEK0GQvhfkXX3m5JVAIkoXV/iN3mEtI2f7TUDkZvPFamivbx8vhKRX+HVj1M4HsGOLyjLPkACZuC9U5fMdVJGbAjDI0dKTC4Pw795yhNm8b0SnzcRTeUSFnTmEAh1JFf+8bTkm7Ne752Lq+CIejOlZkpF/l1GXFFyYAikfC1VZxjxxTWTLDZ6G5/BCSmzQ2pzdAPr1mForT/6eOre1306YST4qiN5tkgZXfqDpoKxswotZa+EqSI1OjL5ttkvyrE+MfgaxwVpdBXlomj/7HRQmA1zVUF2z41e3cqnoro=,iv:/MpqkpJxuJc6j/hfKVWaQjgdDjgIAUHB+Tf5b1WUyhw=,tag:hOMUFpWWUaszNm26NjD+qw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQkZkanpGK3hKbVFpTUcz
            L1cva3pCWVRWTXE2RDZoVlZ6dTI3WGtvN0RjCnFGMXF3N3NUbGhtWldWVTdlUFZY
            TWNnb1MwL0lKVEVxTDVnbkdVd1Y2VlEKLS0tIGRiSE9naXBDY0hzL1pJY1l5K3Za
            ZmtwcVcraHplaFpobnAzVzdCcmMyd1UK1BWsbyr3HzG+xlOhS+XgBqkkTSzdsviF
            0CJOitD+S1RU2YMgL2Uf9cTX1jgQXeI6xNRn7775HPAeRkC+cnD2+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T09:56:20Z"
    mac: ENC[AES256_GCM,data:iODy/7ahJuR21/4kJIOiZcizHpygoTy1Wx+ajcJJQDEy4e7fFyMZvSziCoeTFm4tkBy4/QeIysQNYqimO8wVJrIxge1AWTMKrmQ+mcb8dx2xKzex37+vK/+fap5FvSiZMoFHZ3VFl8/ScpYxhxBg2Fkkq5YPs2iFrosfsPI8n00=,iv:SDAI0egXJ3viaCcZj4c0C8qicK+VdN6KKdy7/ZgqxEg=,tag:YTW64tizEYDCdAmZFmWjxw==,type:str]
    version: 3.13.2
