apiVersion: v1
kind: Secret
metadata:
    name: hermes-secrets
    namespace: hermes
type: Opaque
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:1qHAFqxYv37GN6Z9C1njc54OjD5kYToR36YAdBap0Kb5U4lenUIVxWfJ,iv:hABWVfWtmKbjM+h8o0hgI6jrKCg2gmZe1ZNBeRtaGO4=,tag:GMu46l9FuwTMK8HWn8J/0A==,type:str]
    API_SERVER_KEY: ENC[AES256_GCM,data:C6IwOJIYjMPjgU1VoCmcor5z/rhmrugFsylan0hA9rXID3u8LgneoScFXfa/CI0o+IMyJ+6iHWS8LlnNU3Z5ig==,iv:ZtANV+54fg/4v5kkimIU48Ltw0ZZBjhoNZmLcZfAw1M=,tag:SYyYzyuHngYjzlWoXigkDg==,type:str]
    HOMEASSISTANT_TOKEN: ENC[AES256_GCM,data:L490RAryqJ9O0Rag4ptMM8TE4ZXWcW1pk5wNwnISOhxqm3XNbRhHpziXaLvUTPwXIbckQ+jhejFX1irFtAlrBHaug+TV1Xg3QBqVyaWOXdZtAyP4hhosydJv2G2VXemTlwonhjQMVqDN/Wyf1p1UjXh7bBaDgpCX2hgR8b8RxlNzwNM2LDuaQsQVQnzqyOUGqycpaND8LNnhV5cHjfJq7skOfGiqKoWjkC5BsKA2u2vQecuN0NG/,iv:kzIBBdKhgOloYPA/IrkJNDGeN4GQTcdcymgLKx8cQ6A=,tag:w6XHfb7uzSzs96xNirG89Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSGZkRy9kT01UaW5jcHN6
            dlk3aTBKY2RKZE9lM0hCdzZ2U3Q5dUVSOUNnCkt2VCtpeExhVXhXeUJLUXZRUVBF
            OW40WHBJREtkTk5TTmFoSEJCKzQyakkKLS0tIGRCelZTTDlMaWVVOWZXSEZpZnVZ
            QlF2Uml0ZHlBNjR0VEdmT1NoTlFMWUEKEItvGXdXXYFaqoeRowG0UxmqyLp+4qw7
            snzE2FTTf7Mx2tUQDPvRMLaxsW2FAG2B4qpkwrBVvkp/1S5vAxs71Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T19:31:10Z"
    mac: ENC[AES256_GCM,data:UNZh6+4/hKmnmHSUjrK72HU2oUFIgzXoahWjF3z9toHnnw9xAKm1MIcbb6CIwV7FQDstTUAi/wc9Jtap1dAxzpNUvHqM7E6t7qkT32YGHKkNH9jbASkHWI11aatVJpFOXmyz4DZIJo174+9J2JKjTuNOdKe1uIoR8A0C3NWNdGg=,iv:gGeZ0RiefHpLZ5iaRFeN8eFXUG71s48ED4UIRibUt7o=,tag:0tprYYib4W5/MplvDL6gnA==,type:str]
    version: 3.13.2
