---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evcc-aggregation-config
  namespace: default
data:
  evcc-influx-aggregate.conf: |
    INFLUX_EVCC_DB="evcc"
    INFLUX_EVCC_USER=""
    INFLUX_EVCC_PASSWORD="none"
    INFLUX_AGGR_DB="evcc_aggr"
    INFLUX_AGGR_USER=""
    INFLUX_AGGR_PASSWORD="none"
    INFLUX_HOST="influx-influxdb.monitoring"
    INFLUX_PORT=8086
    PEAK_POWER_LIMIT=40000
    HOME_BATTERY="false"
    DYNAMIC_TARIFF="false"
    TIMEZONE="Europe/Berlin"
    ENERGY_SAMPLE_INTERVAL="60s"
    TARIFF_PRICE_INTERVAL="15m"
    DEBUG="false"
