apiVersion: v1
kind: ConfigMap
metadata:
    name: evcc-config
    namespace: default
data:
    evcc.yaml: ENC[AES256_GCM,data:Uy4W4U54w0OpTXR8gpmHQln9+9rK3HiX7HTDvUb+B4CTLEiYV1MV3kvPQrlHVfiOWYcNfEEAWl47ystANTOqYTPEXxJkDSVcaajrKdycMcIT6tAWK8ullws3pbKGjZm8Yb1uRuD8AA+uu03tY5CwuMsT8EzXETkGAqn3V3io/y9sP57o2uOuqws1WPe0JQdZA53OevpmFeqjazMRJpThKBtYz4F8t1OFA5r8rh/Fgw8WdS8x1wFe96vUAnFd9iQEdxXyI6EP+wl8H3qGAVPvAsaJByfa99BkpMxDPCE74K/F/3cFgXVoi2hjHAO1zsM3DbPg405+ZmvB9rZkshajFF6/NxP+NS2KHBWzzz7hX6C3uxqTViHYVw5sl5YA35TjvyocAlITYgwEQhGot3aYxjy4m+PxAbYiumetLXkUMWpwCAC2zb26uxUyhbrA2lVz6y1rjZA7EtphVLObuzwY/B2FI8EKrtiAD3AyjuXZOjPiHQPf8I7R3X2Xq3aQeZfwqhp1RsskBv8Dj04rLQET9I94um5W1Nn7X/0WcLtoXbaeaf5gX/rj7Tp2zFCpTLg+KRTrGTWFJCjmZhkOn/0l9PxnE7sYSIw67xd1dJIg88xWB+49aEwmsEeNaXwJTnfkgNNPeu5PEw57JTryxpx20RAQpOBpTVlxbkVlQzj45uAjbTH4o6YJF0Ok2rCsQ7Qe90S7VfsOtAqIbadWsWW3n+Rqc9kNzEQPcTl6TIgGN/qmDj2QpfrDTBAJ67OrKkMGQ6PJbyKpVa3tPTzIhuZwOsp6AxQrft1HmAb+SV2xfEuVpQ6OiTx3cc6XZCfiRbjSPdEOFAWk6GhuX4fTuvJMgZVB8iUeq34tf+Q38VPH+21FZU0zjP13oaxJhkr2h9pVSK5bVoEzIwVdQnixtknBI8zr7qUjwDaDgKNIdc5y4V3ZGqqcoZowwN+iPGC4A39H+uoUzqJgTujT1gDuZoZQO5+r4/DAia6IR973VphbgQnIXIm+Za3hyiQIM9WcKoFvh+kJ6PD/U3lnamBaMsubwvcEji94t1doE8do3fXvYeTR+4KVxVBzKxdaedsCWueWGRUFxVfOnUT1cD7tLvwVyQubWCdIVmYuqVzjo0bhlaAGL8y678JLK1ZRR1ZjGfsErn3gblluyXWk6XEDNWQWauCwBW1Kn+PhDJNaE1Fb880lh4sfCb0AXuCinSa7ZhDmytKZCUoxzjqiRWLH8ehb0wgdkkRY8htpN5hxvB1tDR5nnN0n7VVJtZ0aAuM8EUYGzREp25JovmA=,iv:MVN10Yc2sOKPsMrAN7QUpwg2K6M5bfhB5pDDgv7uIEA=,tag:aczHIoR93l4ELnUKpWJAzg==,type:str]
sops:
    age:
        - recipient: age1f897y4l6lrasc0rcgrkz3q4054rk7ewa6gh7g4zruk0vzjp22a9sl6fr55
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDZSQ293MVFGc2puRm1B
            UnBLWlptS1pIc0tTZFU5K1AzWnMwMG1iMUZJClI0Z3VFMUFvVGM1YWFPNVFlRTF4
            cmZkY2pUbEVNS011UFVaMkFpOHB2c28KLS0tIHV4TE5OUHNEWkF0Z2pNalpOWnhE
            QXJzaDgxNDhnTnlJKy9iTGRlbmNJRkEK7XY9Drzq2e6lFzH9R4SEX9Rs4Tnl63W1
            tKoLRAgeoOYv1r0PRQvZjtOVJGY7Bti9toCNKqUzEWZGow1/nigQXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T19:21:37Z"
    mac: ENC[AES256_GCM,data:nEi/4bQhc9QLTiPBSy8Dsyu3sdTexAIMzKW0jWiEyiwLwAvFtjhV1bpIuxQJZ3MxP6D4BUaSg/OByjla2ENQc1d2FOqlhLZcpfmubgJ4I6iMKj8MWCWGm2vA1gQVEyyGdISdsHK9TqiHDnIxInfwQ8VTY1vLdsvYdwzOGeBvyP0=,iv:OVWARyzybKAlBnptb0gXlQyfQwi8RxTqyQZ+3R7pDoc=,tag:7m8hnHmI4Qkwx0N6yd8ltg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
