---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evcc-config
  namespace: default
data:
  evcc.yaml: |
    network:
      schema: http
      host: 0.0.0.0
      port: 7070
    log: info

    meters:
      - name: pv
        type: template
        template: huawei-sun2000-inverter
        usage: pv
        modbus: tcpip
        id: 1
        host: 10.0.10.31
        port: 502
        timeout: 15s

    site:
      title: Home
      meters:
        pv:
          - pv
