---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: evcc
  template:
    metadata:
      annotations:
        reloader.stakater.com/auto: "true"
      labels:
        app.kubernetes.io/name: evcc
    spec:
      containers:
        - name: evcc
          image: evcc/evcc:0.305.1
          ports:
            - name: http
              containerPort: 7070
            - name: huawei
              containerPort: 5021
            - name: marstek
              containerPort: 5022
          volumeMounts:
            - name: config
              mountPath: /etc/evcc.yaml
              subPath: evcc.yaml
              readOnly: true
            - name: data
              mountPath: /root/.evcc
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: evcc-config
        - name: data
          persistentVolumeClaim:
            claimName: evcc-data
