---
apiVersion: v1
kind: Service
metadata:
  name: evcc
  namespace: default
spec:
  ports:
    - port: 7070
      targetPort: http
      protocol: TCP
      name: http
    - port: 5021
      targetPort: modbus
      protocol: TCP
      name: modbus
  selector:
    app.kubernetes.io/name: evcc
