---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 172.16.38.203
  # Local preserves the client IP, which is what lets Plex treat LAN clients as
  # local and direct play instead of remote.
  externalTrafficPolicy: Local
  ports:
    - port: 32400
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: plex
