---
apiVersion: v1
kind: Service
metadata:
  name: adguard-exporter
  namespace: default
  labels:
    app: adguard-exporter
spec:
  type: ClusterIP
  selector:
    app: adguard-exporter
  ports:
    - name: metrics
      port: 9618
      targetPort: metrics
      protocol: TCP
