---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-teslamate
  namespace: default
data:
  teslamate.yaml: |
    version: 1
    metadata:
      name: Teslamate (gitops)
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - model: authentik_core.group
        state: created
        identifiers:
          name: Teslamate
      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          name: Teslamate
        attrs:
          access_token_validity: hours=24
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          basic_auth_enabled: false
          external_host: https://teslamate.${SECRET_LAB_DOMAIN}
          intercept_header_auth: true
          internal_host_ssl_validation: true
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          mode: forward_single
          property_mappings:
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: Proxy outpost']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: Application Entitlements']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''openid''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''email''']]
            - !Find [authentik_providers_oauth2.scopemapping, [name, 'authentik default OAuth Mapping: OpenID ''profile''']]
          refresh_token_validity: days=30
      - model: authentik_core.application
        state: present
        identifiers:
          slug: teslamate
        attrs:
          meta_hide: false
          name: Teslamate
          open_in_new_tab: false
          policy_engine_mode: any
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, Teslamate]]
      - model: authentik_policies.policybinding
        state: present
        identifiers:
          target: !Find [authentik_core.application, [slug, teslamate]]
          order: 0
          group: !Find [authentik_core.group, [name, Teslamate]]
        attrs:
          enabled: true
          negate: false
          failure_result: false
          timeout: 30
